export const buildings = [
  {
    id: 1,
    name: "Edificio 1",
    subtitle: "Arquitectura",
    x: 2030,
    y: 3750,
    radius: 100,
    images: [{ source: require("../assets/Arquitectura_1.jpeg"), fit: "cover" },
    { source: require("../assets/Arquitectura_3D.jpeg"), fit: "cover" }],
    floors: {
      "Piso 1": [{ name: "Papeleria", description: "Establecimiento comercial para suplir materiales Universitarios   -  Horarios: 8:00AM - 6:00PM " }],
      "Mini Teatro": [{ name: "Anfiteatro Principal", description: "Espacio para realizar eventos artisticos. - Horarios: 8:00AM - 6:00PM" }]
    },
  },

  {
    id: 2,
    name: "Edificio 2",
    subtitle: "Tecnología",
    x: 2560,
    y: 3480,
    radius: 100,
    images: [{ source: require("../assets/Edificio_2_mejor.jpeg"), fit: "cover" },
    { source: require("../assets/Cajero_bhd_edificio_2.jpeg"), fit: "cover" },],
    floors: {
      "Piso 1": [
        { name: "Baños"},
        { name: "Vending Machine" },
        { name: "Cajero BHD", description: "Cajero automático del Banco BHD para retiros, consultas y transacciones básicas." },
        { name: "Aula 101", capacity: 30 },
        { name: "Aula 102", capacity: 28 },
        { name: "Archivo", description: "Espacio destinado al almacenamiento y organización de documentos administrativos." },
        { name: "Aula 103", capacity: 35 },
        { name: "Soporte Tecnico" },
        { name: "Aula 104", capacity: 30 },
        { name: "Salón de Profesores", description: "Área privada donde los docentes pueden reunirse, descansar, preparar clases o trabajar." },
        { name: "Unidad de Calidad Académica (Civil)", description:"Oficina dedicada a la supervisión de los estándares académicos del programa de Ingeniería Civil." },
        { name: "Departamento de Investigaciones", description:"Unidad encargada de proyectos de investigación, apoyo técnico, asesorías y gestión científica." },
        { name: "Aula 105", capacity: 32 },
        { name: "Facultad Ciencias Agropecuarias y Recursos Naturales", description: "Oficina administrativa para programas, coordinaciones y servicios relacionados a esta facultad." },
        { name: "Aula 106", capacity: 25 },
        { name: "Tutorías", description:"Espacio dedicado a asesorías académicas personalizadas para estudiantes." },
        { name: "Laboratorio de Saneamiento y Calidad de Agua", capacity: 20, description:"Administración y coordinación académica del programa de Ingeniería Geomática." },
        { name: "Aula 107", capacity: 30 },
        { name: "Aula 109", capacity: 30 },
        { name: "Aula 110", capacity: 30 },
        { name: "Aula 111", capacity: 30 },
        { name: "Aula 112", capacity: 30 },
        { name: "Aula 113", capacity: 30 },
        { name: "Laboratorio de Geología y Petrografia"},
        { name: "Escuela de Ingeniería Geomatica", description: "Administración y coordinación académica del programa de Ingeniería Geomática."},
        { name: "Escuela de Informática ", description: "Coordinación académica y administrativa de la carrera de Informática."},
        { name: "Escuela de Ingeniería Civil", description: "Administración del programa de Ingeniería Civil: coordinación, servicios y apoyo académico."},
        { name: "Escuela de Ingeniería Industrial", description: "Oficina encargada de la coordinación de la carrera de Ingeniería Industrial."},
        { name: "Archivo Ing. Civil", description: "Depósito de documentos, planos, informes y expedientes relacionados a Ingeniería Civil."},
        { name: "CIEIEA-UNPHU", description: "Centro de Investigación y Estudio en Ingeniería, Ambiente y Agua. Espacio dedicado a análisis técnicos y estudios medioambientales."},
        { name: "Salón de Reuniones", description: "Sala destinada para encuentros académicos, juntas, presentaciones internas o reuniones administrativas." },
        { name: "ACI", description:"Oficina vinculada a acreditación y certificación de programas de ingeniería (American Concrete Institute)." },
        { name: "Iberolab", description:"Centro orientado a simulaciones, proyectos o prácticas relacionadas a ciencias aplicadas o tecnología." },
        { name: "Laboratorio de Investigaciones en Ciencias Básicas", capacity: 18 },
        { name: "Salida de Emergencia", description:"Punto de evacuación oficial para uso en situaciones de emergencia." },
      ],
      "Piso 2": [
        { name: "Aula 208", capacity: 30 },
        { name: "Aula 211", capacity: 30 },
        { name: "Aula 212", capacity: 30 },
        { name: "Aula 213", capacity: 30 },
        { name: "Aula 214", capacity: 30 },
        { name: "Aula 215", capacity: 30 },
        { name: "Aula 216", capacity: 30 },
        { name: "Aula 217", capacity: 30 },
        { name: "Aula 218", capacity: 30 },
        { name: "Aula 219", capacity: 30 },
        { name: "Aula 220", capacity: 30 },
        { name: "Baños" },
        { name: "Departamento de Matemáticas", description:"Oficina académica para consultas, coordinación docente y administración del área de Matemáticas." },
      ],
      "Piso 3": [
        { name: "Comedor de profesores", description: "Área reservada para que los docentes puedan comer, descansar o reunirse." },
        { name: "Baños" },
        { name: "Recepcion y despacho de productos quimicos", description: "Zona para control seguro, registro y entrega de materiales e insumos químicos usados en prácticas." },
        { name: "Lab-Quimica General II 238", capacity: 20 },
        { name: "Escuela de Quimica" },
        { name: "Lab de quimica general I 237", capacity: 20 },
        { name: "Lab de Quimica Ingenieria Quimica 236", capacity: 18 },
        { name: "Lab. Quimica Salon de profesores - tutoria 235" },
        { name: "Lab de quimica - Quimica organica - Bioquimica 234", capacity: 18},
        { name: "Lab Quimica analitica Cualitativa - Cuantitativa 233", capacity: 18},
        { name: "Lab Fisica FIS-301", capacity: 24 },
        { name: "LAB FIS-302", capacity: 24 },
        { name: "LAB FIS-303", capacity: 24 },
        { name: "Salon de reuniones de profesores" },
        { name: "Salon de tutorias" },
      ],
    },
  },

  {
    id: 3,
    name: "Edificio 3",
    subtitle: "Biblioteca",
    x: 2130,
    y: 2920,
    radius: 80,
    images: [
      { source: require("../assets/Biblioteca_cos.jpeg"), fit: "cover" },

    ],
    floors: {
      Cosmetologia: [
        { name: "Direccion de educacion continuada", description:"Oficina encargada de diplomados, cursos técnicos, talleres y programas de formación continua." },
        { name: "Area de caja", description:"Punto de pago para servicios, cursos y trámites administrativos." },
        { name: "Recepcion", description:"Área de bienvenida y orientación para estudiantes y visitantes." },
        { name: "Medicina Estetica", description:"Área especializada en procedimientos estéticos." },
        { name: "Cosmetologia", description:"Sala de prácticas y servicios relacionados a tratamientos estéticos profesionales." },
        { name: "Almacen de productos", description:"Depósito donde se guardan suministros, equipos y materiales." },
        { name: "Laboratorio 01", capacity: 18 },
        { name: "Laboratorio 02 – Salón de Práctica B", capacity: 18 },
        { name: "Oficina coordinadora de diplomado", description:"Área administrativa encargada de gestionar programas avanzados de formación." },
        { name: "Aula 01", capacity: 25 },
        { name: "Aula 02", capacity: 25 },
        { name: "Baños" },
        { name: "Oficina de Educación Continuada", description:"Espacio de operación administrativa de todos los programas extracurriculares." },
        { name: "Oficina de secretaria", description:"Punto de apoyo administrativo para estudiantes y docentes del área." },
      ],
      "Biblioteca": [
        { name: "Recepcion", description:"Punto principal de atención para préstamos, información y servicios bibliotecarios." },
        { name: "Tesis Y Trabajo de Grado Hemeroteca", description:"Área para consulta de investigaciones, publicaciones académicas y archivos físicos." },
        { name: "Catologo en Linea", description: "Estaciones para búsqueda digital de libros, investigaciones y recursos bibliográficos." },
        { name: "Sala de Preferencia", description:"Espacio cómodo y silencioso para lectura sin interrupciones." },
        { name: "Sala Digital", description:"Área con computadoras para investigación, trabajos." },
        { name: "Servicio Fotocopia", description:"Centro de copiado e impresión para estudiantes y docentes. - no es la version final" },
        { name: "Baños" },
        { name: "Oficinas Administrativas", description:"Oficinas del personal encargado de operar y gestionar la biblioteca." },
        { name: "Salon de Conferencias Ing Mario Cabrera", description:"Espacio para charlas, exposiciones, actividades académicas y presentaciones." },
        { name: "Comunicacion y Mercadeo", description:"Departamento encargado de la imagen institucional, redes y comunicaciones internas. no es la version final" },
        { name: "Salon de Entrenamiento Docente", description:"Sala para talleres, capacitaciones y formación de profesores."},
        { name: "Aula 102", capacity: 30 },
      ],
      "Biblioteca - Piso 2": [
        { name: "Espacio de lectura", description:"Área tranquila para estudio individual y lectura libre." },
        { name: 'Sala de Estudios Colectivos "Dra. Estervina Matos"', description:"Sala diseñada para grupos de estudio, reuniones académicas y trabajos colaborativos."},
      ],
      "Piso 3": [{ name: "Sala de juntas", description:"Sala para reuniones importantes, sesiones administrativas y planificación académica." }, { name: "FUDPHU - (Fundacion UNPHU)", description:"Área destinada a actividades institucionales, apoyo estudiantil y proyectos comunitarios." }],
      "Piso 4": [
        { name: "Vicerrectoria de postgrado (clinica odontologica de postgrado)", description:"Oficina principal encargada de la administración del postgrado y especialidades." },
        { name: "Aula 401", capacity: 25 },
        { name: "Aula 402", capacity: 25 },
        { name: "Aula 406", capacity: 20 },
        { name: "Aula 407", capacity: 20 },
        { name: "Aula 408", capacity: 20 },
        { name: "Aula 411", capacity: 20 },
        { name: "Baños" },
        { name: "CAICOC", description: "Centro Avanzado de Investigacion y Capacitacion Odontologica Continua"},
        { name: "Ascensor", description:"Acceso al elevador del edificio." },
        { name: "Direccion de desarollo", description:"Oficina dedicada a planificación estratégica, proyectos y crecimiento institucional." },
        { name: "Aula 409", capacity: 20 },
        { name: "Postgrado", description:"Área administrativa destinada a maestrías y programas avanzados." },
        { name: "Oficinas administrativas", description:"Espacios para personal docente y de gestión del área de postgrado." },
      ],
    },
  },

  {
    id: 4,
    name: "Edificio 4",
    subtitle: "Derecho",
    x: 2740,
    y: 2690,
    radius: 90,
    images: [{ source: require("../assets/Edificio_4_mejor.jpeg"), fit: "cover" },
    { source: require("../assets/Edificio_4_2.jpeg"), fit: "cover" },

    ],
    floors: {
      "Piso 1": [
        { name: "Vending machine" },
        { name: "Investigaciones F.HYE", description:"Unidad dedicada a proyectos académicos y estudios desarrollados por la Facultad de Humanidades y Educación." },
        { name: "Cafe Santo Domingo" },
        { name: "Departamento de Tec. Y Audiovisuales", description:"Oficina encargada de gestionar equipos audiovisuales, soporte técnico en eventos y recursos multimedia para docentes." },
        { name: "Facultad de Ciencias Juridicas y Politicas", description:"Oficina administrativa responsable de los programas de Derecho y Ciencias Políticas." },
        { name: "Facultad de ciencias economicas y sociales", description:"Administración de programas y actividades académicas de esta facultad." },
        { name: "Acreditadora", description:"Espacio asociado a procesos de evaluación, calidad académica y certificación institucional." },
        { name: "Sala Max Henríquez Ureña", description:"Sala de conferencias usada para charlas, presentaciones, defensas de tesis y eventos." },
        { name: "Dispensario Médico", description:"Unidad de atención médica primaria para emergencias, chequeos rápidos y servicios básicos de salud." },
        { name: "Aula modular", capacity: 40 },
        { name: "Amadita", description: "Laboratorio clínico que ofrece análisis médicos — horario: lunes a viernes 7:00 AM a 3:00 PM." },
        { name: "Baños" },
        { name: "Escuela de hoteleria y turismo", description:"Área administrativa encargada de coordinar las carreras de Turismo, Hotelería y afines." },
        { name: "Seguridad", description:"Punto de control y vigilancia, encargado de la seguridad del área." },
        { name: "Facultad de humanidades y educacion", description:"Administración y gestión de los programas vinculados a humanidades." },
      ],
      "Piso 2": [
        { name: "Coordinacion Academica", description:"Oficina que gestiona horarios, asignaciones docentes y procesos académicos internos." },
        { name: "Escuela de Educacion", description:"Administración encargada de los programas y servicios del área educativa." },
        { name: "Baños" },
        { name: "Aula 200", capacity: 30 },
        { name: "Aula 201", capacity: 30 },
        { name: "Aula 202", capacity: 30 },
        { name: "Aula 203", capacity: 30 },
        { name: "Asistente Academico Encargado de Evaluacion Cocurricular", description:"Oficina responsable de registrar, supervisar y validar actividades extracurriculares de los estudiantes." },
        { name: "Departamento de Lenguas Extranjeras", description:"Área administrativa que coordina cursos y programas de idiomas."},
        { name: "Aula 204", capacity: 30 },
        { name: "Aula 205", capacity: 30 },
        { name: "Coordinacion de Educacion Especial", description:"Oficina dedicada al programa académico de Educación Especial." },
        { name: "Aula 206", capacity: 31 },
        { name: "Estrado de Politica Forense", description:"Sala donde se realizan simulaciones legales, prácticas forenses y actividades académicas jurídicas." },
        { name: "Direccion de Tecnologia Educativa", description:"Unidad encargada del desarrollo de plataformas, herramientas y recursos digitales." },
        { name: "Departamento de Tecnologia Educativa", description:"Área operativa que apoya docentes en el uso de tecnología para la enseñanza." },
      ],
      "Piso 3": [
        { name: "Aula 301", capacity: 30 },
        { name: "Aula 302", capacity: 30 },
        { name: "Aula 303", capacity: 30 },
        { name: "Aula 304", capacity: 30 },
        { name: "Aula 305", capacity: 30 },
        { name: "Aula 306", capacity: 30 },
        { name: "Aula 307", capacity: 30 },
        { name: "Aula 308", capacity: 30 },
        { name: "Baños" },
        { name: "Coordinación de prácticas y pasantía", description:"Oficina que gestiona prácticas profesionales y pasantías para los estudiantes."},
        { name: "Oficina Docente", description:"Área de trabajo para profesores, asesorías y reuniones académicas."},
        { name: "Consultoria jurídica", description:"Oficina orientada a brindar servicios legales universitarios, asesoría o apoyo jurídico."},
        { name: "Cocina", description:"Área destinada a preparación de alimentos internos, apoyo a eventos o personal administrativo." },
        { name: "Departamento de Letras, Filosofía e Historia y Geografía", description:"Coordinación académica encargada de programas de humanidades."},
        { name: "Laboratorio CES - 309 "},
        { name: "Laboratorio CES - 310 "},
        { name: "Aula 311", capacity: 30 },
        { name: "Aula 312", capacity: 30 },
        { name: "Escuela de Psicologia" },
      ],
    },
  },

  {
    id: 5,
    name: "Edificio 5",
    subtitle: "Auditorio",
    x: 2470,
    y: 2250,
    radius: 90,
    images: [{ source: require("../assets/Auditorio_2.jpeg"), fit: "fill" }],
    floors: {
      "piso 1": [{ name: "Salón de Conferencias", description: 30, description: "Área destinada a conferencias, presentaciones académicas y actividades institucionales." }],
    },
  },

  {
    id: 6,
    name: "Edificio 6",
    subtitle: "Ingenieria Industrial",
    x: 1610,
    y: 1830,
    radius: 80,
    images: [{ source: require("../assets/Edificio-6.jpg"), fit: "cover" }],
    floors: {
      "Piso 1": [
        { name: "Comedor para colaboradores", description:"Área destinada exclusivamente para que el personal y colaboradores tomen sus alimentos - Horario: 11:00 AM – 3:00 PM." },
        { name: "Aula 101", capacity: 30, projector: false },
        { name: "Aula 102", capacity: 30, AC: false, projector: false },
        { name: "Aula 103", capacity: 30 },
        { name: "Aula 104", capacity: 30 },
        { name: "Aula 105", capacity: 30 },
        { name: "Aula 106", capacity: 30 },
        { name: "Laboratorio Gastronomico Mike Mercedes", capacity: 18 },
      ],
      "Ing. Industrial": [
        { name: "Aula 201", capacity: 28 },
        { name: "Aula 202", capacity: 28 },
        { name: "Aula 203", capacity: 28 },
      ],
    },
  },

  {
    id: 7,
    name: "Edificio 7",
    subtitle: "Pre-grado Universitario",
    x: 1550,
    y: 2175,
    radius: 80,
    images: [{ source: require("../assets/Edificio_7_mejor.jpeg"), fit: "cover" }],
    floors: {
      "Piso 1": [
        { name: "Recepcion", description:"Punto principal de información, asistencias y servicios." },
        { name: "Vending machine" },
        { name: "Cafeteria" },
        { name: "Aula 06", capacity: 30, AC: false, projector: false},
        { name: "Aula 07", capacity: 30, AC: false, projector: false },
        { name: "Aula 08", capacity: 30, AC: false, projector: false },
        { name: "Aula 09", capacity: 30, AC: false, projector: false },
        { name: "Colegio Preuniversitario Dr. Luis Alfredo Duvergé Mejía", description:"Institución académica interna que ofrece educación a nivel escolar/preuniversitario." },
        { name: "Baños" },
        { name: "Aula 05", capacity: 30, AC: false, projector: false },
        { name: "Aula 04", capacity: 30, AC: false, projector: false },
        { name: "Aula 103", capacity: 30, AC: false, projector: false },
        { name: "Aula 102", capacity: 30, AC: false, projector: false },
        { name: "Aula 101 - Centro de computo 1", capacity: 28 },
        { name: "Aula 111", capacity: 28, AC: false, projector: false },
        { name: "Aula 112", capacity: 28, AC: false, projector: false },
        { name: "Aula 113", capacity: 28, AC: false, projector: false },
        { name: "Aula 114", capacity: 28, AC: false, projector: false },
        { name: "Aula 115", capacity: 28, AC: false, projector: false },
        { name: "Aula 116", capacity: 28, AC: false, projector: false },
        { name: "Aula 117", capacity: 28, AC: false, projector: false },
        { name: "Aula 118", capacity: 28, AC: false, projector: false },
        { name: "Aula 119", capacity: 28, AC: false, projector: false },
        { name: "Aula 120", capacity: 28, AC: false, projector: false },
        { name: "Aula 121", capacity: 28, AC: false, projector: false },
        { name: "Area Verde", description:"Zona abierta con césped y árboles, usada para descanso, estudio al aire libre y recreación." },
      ],
    },
  },

  {
    id: 8,
    name: "Edificio 8",
    x: 2210,
    y: 1700,
    radius: 100,
    images: [{ source: require("../assets/Edificio_8_mejor.jpeg"), fit: "cover" }],
    floors: {
      "Piso 1": [
        { name: "Economato", description:"ESpacio de venta de articulos de estudio." },
        { name: "Comision de Horarios", description:"Oficina responsable de la organización general de Asignaturas y horarios académicos ", ac: true, projector: true},
        { name: "Departamento de cobro de matricula y Caja", description:"Área encargada de pagos, facturación, notas de crédito y servicios financieros del estudiante." },
        { name: "Vending machine" },
        { name: "Baños" },
        { name: "Direccion de Gestion Humana, tramite y archivos", description:"Oficina de recursos humanos: solicitudes, registros de personal, expedientes y procesos administrativos." },
        { name: "Computo", description:"Sala de sistemas para soporte tecnológico o servicios administrativos internos." },
        { name: "Registro y evaluaciones", description:"Departamento encargado de récord académico, certificaciones, validaciones y procesos estudiantiles." },
        { name: "Departamento TIC", description:"Unidad que administra infraestructura tecnológica, redes y soporte del campus." },
        { name: "EPS", description: "Centro de recepción y envío de paquetes para estudiantes y colaboradores del campus." },
        { name: "Admisiones", description:"Oficina principal para procesos de ingreso, información y orientación a futuros estudiantes." },
        { name: "Vending machine 2" },
        { name: "Administrativa y Financiera", description:"Unidad encargada de presupuestos, cobros, pagos y gestión económica institucional."},
        { name: "Decanato de bienestar estudiantil", description:"Área que brinda apoyo psicológico, social, deportivo y académico a los estudiantes." },
        { name: "Departamento de contabilidad", description:"Encargado de registros financieros, balances y control contable." },
        { name: "Departamento de Contraloria", description:"Oficina que supervisa procesos financieros y cumplimiento institucional." },
      ],
      "Piso 2": [
        { name: "Unidad de evaluacion y desarrollo docente", description:"Área dedicada a capacitar y evaluar al cuerpo docente." },
        { name: "Vicerrectoria Academica", description:"Dirección principal encargada de supervisar todos los procesos académicos de la universidad." },
        { name: "Aula Urania Montas", capacity: 50 },
        { name: "Laboratorio de Fisiologia 1", capacity: 20 },
        { name: "Lab de Fisiologia 2", capacity: 20 },
        { name: "Lab de Farmacia", capacity: 18 },
        { name: "Lab de Farmacia 2", capacity: 18 },
        { name: "COSMOS (Centro de operaciones en simulacion medica)", description:"Centro de simulación médica avanzado para prácticas clínicas y procedimientos médicos en escenarios controlados." },
      ],
    },
  },

  {
    id: 9,
    name: "Edificio 9",
    subtitle: "Anatomía",
    x: 1440,
    y: 1530,
    radius: 100,
    images: [{ source: require("../assets/Edificio_9_lowkey_mejor.jpeg"), fit: "cover" }],
    floors: {
      "Piso 1": [
        { name: "Laboratorio de anatomica", capacity: 18 },
        { name: "Instituto de anatomia Dr. Alejando capellan diaz", description:"Área dedicada a estudios anatómicos, preparación de materiales y manejo académico del programa." },
      ],
    },
  },

  {
    id: 10,
    name: "Edificio 10",
    subtitle: "Veterinaria",
    x: 2620,
    y: 4804,
    radius: 80,
    images: [{ source: require("../assets/Edificio-10.jpeg"), fit: "cover" },
    { source: require("../assets/UnphuPetShot.jpeg"), fit: "cover" },],
    floors: {
        "Unphu PetShop": [
            { name: "Clinica Veterinaria", description: "Espacio clínico dedicado al cuidado, consultas y procedimientos veterinarios - Horarios: Lunes a Viernes - Sabados hasta medio dia (Solo con cita previa) 8:00 AM a 4:00 PM" }
          ],
      "Piso 1": [
        { name: "Laboratorio de anatomia", capacity: 20 },
        { name: "Baños" },
        { name: "Escuela de Veterinaria" },
      ],
      "Piso 2": [
        { name: "Aula 01", capacity: 30 },
        { name: "Aula 02", capacity: 28 },
        { name: "Aula 03", capacity: 32 },
        { name: "Aula 04", capacity: 25 },
      ],
    },
  },

  {
    id: 11,
    name: "Edificio 11",
    subtitle: "Odontología",
    x: 2410,
    y: 4830,
    radius: 90,
    images: [{ source: require("../assets/Edificio-11.jpg"), fit: "cover" }],
    floors: {
      "Piso 1": [
        { name: "Área de Información", description:"Recepción general para orientación, citas y atención al cliente." },
        { name: "Area de cobros (caja, archivos)", description:"Espacio destinado a pagos, facturación." },
        { name: "Clinica de Odontologia", description:"Área para prácticas clínicas, consultas, evaluaciones y tratamientos dentales." },
        { name: "Estacion de carga de celulares", description:"Zona con puertos de carga para dispositivos." },
        { name: "Vending machine" },
        { name: "Baños" },
      ],
      "piso 2": [
        { name: "Salón de reuniones" },
        { name: "Administración" },
        { name: "Laboratorio de investigaciones odontológicas" },
        { name: "Laboratorio de Odontología" },
        { name: "Aula 201", capacity: 18 },
        { name: "Aula 202", capacity: 18 },
        { name: "Aula 203", capacity: 18 },
        { name: "Baños" },
      ],
    },
  },

  {

  id: 13,
  name: "Edificio 12",
  subtitle: "MYPYMES",
  x: 1760,
  y: 2670,
  radius: 80,
  images: [{ source: require("../assets/Edificio_12.jpeg"), fit: "cover" }],
  floors: {
  "Piso 1": [
    { name: "Recepcion" },
     ],
   },
  },



  {
    id: 12,
    name: "Edificio 6A",
    x: 1630,
    y: 1650,
    radius: 80,
    images: [{ source: require("../assets/Edificio_6A.jpeg"), fit: "cover" }],
    floors: {
      "Piso 1": [
        { name: "Aula 108", capacity: 30, AC: false, projector: false},
        { name: "Aula 109", capacity: 30, AC: false, projector: false },
        { name: "Aula 110", capacity: 30, AC: false, projector: false },
        { name: "Aula 111", capacity: 25, AC: false, projector: false },
        { name: "Aula 112", capacity: 25, AC: false, projector: false  },
        { name: "Aula 113", capacity: 25, AC: false, projector: false  },
        { name: "Aula 201", capacity: 25, AC: false, projector: false  },
        { name: "Aula 206", capacity: 25, AC: false, projector: false  },
      ],
      "Piso 2": [
        { name: "Aula 204", capacity: 25, AC: false, projector: false  },
        { name: "Aula 205", capacity: 25, AC: false, projector: false  },
        { name: "Aula 207", capacity: 25, AC: false, projector: false  },
        { name: "Aula 208", capacity: 25, AC: false, projector: false  },
        { name: "Aula 209", capacity: 25, AC: false, projector: false  },
      ],
      "Piso 3": [
        { name: "Aula 301", capacity: 25, AC: false, projector: false  },
        { name: "Aula 302", capacity: 25, AC: false, projector: false  },
        { name: "Aula 303", capacity: 25, AC: false, projector: false  },
        { name: "Aula 304", capacity: 25, AC: false, projector: false  },
        { name: "Aula 305", capacity: 25, AC: false, projector: false  },
        { name: "Aula 306", capacity: 25, AC: false, projector: false  },
      ],
    },
  },

  {
    id: 15,
    name: "Campo de Baseball",
    subtitle: "Complejo Deportivo",
    x: 2450,
    y: 4200,
    radius: 100,
    images: [{ source: require("../assets/Campo_pelota_1.jpeg"), fit: "cover" },
    { source: require("../assets/campo_pelota_2.jpeg"), fit: "cover" },
    { source: require("../assets/Campo_pelota_3.jpeg"), fit: "cover" },
    ],
    floors: { Info: [{ name: "Campo Principal", description: "Terreno reglamentario para entrenamientos avanzados, juegos oficiales y actividades deportivas de mayor nivel - Horarios: 7:00AM - 9:00PM" },
    { name: "Campo Infantil", description: "Espacio diseñado para la práctica de béisbol por parte de niños y categorías formativas - Horarios: 7:00AM - 9:00PM" },
    { name: "Campo Intermedio", description: "Área destinada a entrenamientos y juegos de nivel intermedio - Horarios: 7:00AM - 9:00PM" },] },
  },

  {
      id: 22,
      name: "Gimnasio",
      subtitle: "Gimnasio al aire libre",
      x: 1700,
      y: 2970,
      radius: 100,
      images: [{ source: require("../assets/Gimnasio_aireLibre.jpeg"), fit: "cover" }],
      floors: { Info: [{ name: "Gimnasio al aire libre", description: "Espacio diseñado para actividad física al aire libre, equipado con estaciones para ejercicios funcionales y entrenamiento corporal." }] },
    },

  {
    id: 16,
    name: "Barça Academy",
    subtitle: "Academia de Soccer",
    x: 1350,
    y: 4380,
    radius: 120,
    images: [{ source: require("../assets/Big_field.jpeg"), fit: "cover" },
    { source: require("../assets/Small_campus.jpeg"), fit: "cover" }],

    floors: {
      "Piso 1": [
        { name: "Area de recepcion" },
        { name: "Baños" },
        { name: "Campo pequeño"},
        { name: "Campo grande" },
      ],
    },
  },

    {

    id: 19,
    name: "Seguridad",
    subtitle: "Edificio de Seguridad",
    x: 1585,
    y: 2637,
    radius: 80,
    images: [{ source: require("../assets/Edificio_12.jpeg"), fit: "cover" }],
    floors: {
    "Piso 1": [
      { name: "Recepcion" },
       ],
     },
    },

      {

        id: 20,
        name: "Cancha de Basketball",
        subtitle: "Área Deportiva",
        x: 1700,
        y: 3280,
        radius: 80,
        images: [{ source: require("../assets/Cancha_basketball.jpeg"), fit: "cover" }],
        floors: {
        "Basketball": [
          { name: "Cancha Principal", description: "Horarios: 7:00AM - 9:00PM" },
           ],
         },
        },

            {

                id: 21,
                name: "Cancha de Tennis",
                subtitle: "Área Deportiva",
                x: 1497,
                y: 3530,
                radius: 80,
                images: [{ source: require("../assets/Cancha_basketball.jpeg"), fit: "cover" }],
                floors: {
                "Tennis": [
                  { name: "Cancha Principal", description: "Horarios: 7:00AM - 9:00PM" },
                   ],
                 },
                },

                {

                                id: 23,
                                id: 23,
                                name: "Cancha de Fútbol",
                                subtitle: "Área Deportiva",
                                x: 1720,
                                y: 1070,
                                radius: 100,
                                images: [{ source: require("../assets/campo_grande_atras.jpeg"), fit: "cover" },
                                { source: require("../assets/campo_atras_3.jpeg"), fit: "cover" },
                               ],
                                floors: {
                                "Fútbol": [
                                  { name: "Campo Grande", description: "Horarios: 7:00AM - 9:00PM" },
                                   ],
                                 },
                                },
  {
    id: 17,
    name: "Bosquecito",
    subtitle: "Área Natural del Campus",
    x: 2730,
    y: 3130,
    radius: 100,
    images: [{ source: require("../assets/Bosquecito.jpeg"), fit: "cover" },
    { source: require("../assets/Bosquecito_2.jpeg"), fit: "cover" },
    { source: require("../assets/Cajero_bhd_bosquecito.jpeg"), fit: "cover" },

    ],
    floors: {
      Info: [
        { name: "Area Verde", description: "Espacio natural rodeado de árboles, ideal para estudiar, relajarse o disfrutar de un ambiente tranquilo al aire libre." }
      ],
    },
  },
];


export const foodPlaza = [
  {
    id: 100,
    name: "Plaza de Comida",
    x: 1755,
    y: 3520,
    radius: 90,
    vendors: {
      "Uni Martini": {
        schedule: "12:00 PM - 10:00 PM",
        images: [{ source: require("../assets/pizza.jpg"), fit: "cover" }],
        menu: [
          { item: "Pizza Peperoni (slice)", price: "RD$ 125" },
          { item: "Pizza Suprema (slice)", price: "RD$ 150" },
          { item: "Pizza Hawaiana (slice)", price: "RD$ 140" },
          { item: "Calzone de Carne", price: "RD$ 250" },
          { item: "Lasagna", price: "RD$ 300" },
          { item: "Pan de Ajo (4 piezas)", price: "RD$ 100" },
          { item: "Ensalada César", price: "RD$ 220" },
          { item: "Raviolis", price: "RD$ 280" },
          { item: "Pasta Alfredo", price: "RD$ 320" },
          { item: "Refresco 2 Litros", price: "RD$ 150" },
        ],
      },

      "Rico Hot Dog": {
        schedule: "10:00 AM - 9:00 PM",
        images: [{ source: require("../assets/hotdog.jpg"), fit: "contain" }],
        menu: [
          { item: "Hot Dog Clásico", price: "RD$ 150" },
          { item: "Hot Dog Jumbo", price: "RD$ 175" },
          { item: "Chimi de Pierna", price: "RD$ 200" },
          { item: "Chimi de Pollo", price: "RD$ 190" },
          { item: "Yaroa de Papas", price: "RD$ 250" },
          { item: "Yaroa de Plátano Maduro", price: "RD$ 250" },
          { item: "Salchipapas", price: "RD$ 180" },
          { item: "Empanada de Pollo", price: "RD$ 75" },
          { item: "Quipes", price: "RD$ 75" },
          { item: "Refresco", price: "RD$ 50" },
          { item: "Jugo Natural", price: "RD$ 70" },
          { item: "Agua", price: "RD$ 40" },
        ],
      },
      "Helados Bon": {
        schedule: "11:00 AM - 8:00 PM",
        images: [{ source: require("../assets/Bon.jpg"), fit: "cover" }],
        menu: [
          { item: "Barquilla Sencilla", price: "RD$ 100" },
          { item: "Barquilla Doble", price: "RD$ 180" },
          { item: "Tinita", price: "RD$ 120" },
          { item: "Sundae", price: "RD$ 200" },
          { item: "Banana Split", price: "RD$ 275" },
          { item: "Malteada", price: "RD$ 225" },
          { item: "Paleta de Frutas", price: "RD$ 80" },
          { item: "Copa de Helado", price: "RD$ 190" },
          { item: "Litro de Helado", price: "RD$ 450" },
          { item: "Brownie con Helado", price: "RD$ 250" },
        ],
      },

      "Yova's Desserts": {
        schedule: "9:00 AM - 7:00 PM",
        images: [{ source: require("../assets/helado.jpg"), fit: "cover" }],
        menu: [
          { item: "Strawberry Cheese Cake", price: "RD$ 150" },
          { item: "Nutella", price: "RD$ 150" },
          { item: "Pistacho", price: "RD$ 150" },
          { item: "Dulce de Leche", price: "RD$ 150" },
          { item: "Ponche", price: "RD$ 150" },
          { item: "Chinola Crema", price: "RD$ 150" },
          { item: "Kit Kat", price: "RD$ 150" },
          { item: "Cookies & Cream", price: "RD$ 150" },
          { item: "Batata Coco", price: "RD$ 120" },
          { item: "Coco", price: "RD$ 120" },
          { item: "Cremoso Mango", price: "RD$ 120" },
          { item: "Fresa", price: "RD$ 90" },
          { item: "Tamarindo", price: "RD$ 90" },
          { item: "Chinola", price: "RD$ 90" },
          { item: "Sandia Limon", price: "RD$ 90" },
          { item: "Mango Fresa", price: "RD$ 90" },

        ],
      },
    },
  },


  //    SEGUNDA CAFETERÍA

  {
    id: 101,
    name: "Cafetería - Edificio 2",
    x: 2250,
    y: 3450,
    radius: 90,
    vendors: {
      "Cafetería - Buffet": {
        schedule: "12:00 PM - 10:00 PM",
        images: [{ source: require("../assets/pizza.jpg"), fit: "cover" }],
        menu: [
          { item: "Pizza Peperoni (slice)", price: "RD$ 125" },
          { item: "Pizza Suprema (slice)", price: "RD$ 150" },
          { item: "Pizza Hawaiana (slice)", price: "RD$ 140" },
          { item: "Calzone de Carne", price: "RD$ 250" },
          { item: "Lasagna", price: "RD$ 300" },
          { item: "Pan de Ajo (4 piezas)", price: "RD$ 100" },
          { item: "Ensalada César", price: "RD$ 220" },
          { item: "Raviolis", price: "RD$ 280" },
          { item: "Pasta Alfredo", price: "RD$ 320" },
          { item: "Refresco 2 Litros", price: "RD$ 150" },
        ],
      },
        "Cafeteria - 2": {
        schedule: "12:00 PM - 10:00 PM",
        images: [{ source: require("../assets/pizza.jpg"), fit: "cover" }],
        menu: [
          { item: "Pizza Peperoni (slice)", price: "RD$ 125" },
          ],
      },
    },
  },
];
