import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  fallbackContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f3f3f3",
    padding: 20,
  },
  fallbackText: {
    fontSize: 18,
    fontWeight: "700",
    color: "#333",
    textAlign: "center",
  },
  fallbackButton: {
    marginTop: 18,
    backgroundColor: "#f59e0b",
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
  },
  fallbackButtonText: {
    color: "#fff",
    fontWeight: "800",
  },
  container: {
    flex: 1,
    backgroundColor: "#f3f3f3",
  },
  header: {
    height: 80,
    backgroundColor: "#f59e0b",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
  },
  backBtn: {
    marginRight: 10,
  },
  backText: {
    fontSize: 50,
    color: "#fff",
    fontWeight: "800",
  },
  headerTitle: {
    top: 5,
    left: 10,
    color: "#fff",
    fontSize: 25,
    fontWeight: "800",
  },
  scrollContent: {
    padding: 16,
    paddingBottom: 30,
  },
  pageTitle: {
    fontSize: 24,
    fontWeight: "800",
    color: "#111",
  },
  pageSubtitle: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
    marginBottom: 16,
  },
  formCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
  },
  sectionHeader: {
    marginTop: 10,
    marginBottom: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#222",
  },
  addButton: {
    backgroundColor: "#f59e0b",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  addButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
  },
  vendorCard: {
    backgroundColor: "#fafafa",
    borderWidth: 1,
    borderColor: "#ececec",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "center",
  },
  vendorCardActive: {
    borderColor: "#f59e0b",
    borderWidth: 2,
    backgroundColor: "#fffaf0",
  },
  vendorTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: "#111",
  },
  vendorSub: {
    fontSize: 13,
    color: "#666",
    marginTop: 3,
  },
  vendorMeta: {
    fontSize: 12,
    color: "#f59e0b",
    marginTop: 5,
    fontWeight: "700",
  },
  arrow: {
    fontSize: 26,
    color: "#666",
    marginLeft: 10,
  },
  editorWrap: {
    marginTop: 18,
    borderTopWidth: 1,
    borderTopColor: "#ececec",
    paddingTop: 16,
  },
  editorTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#111",
    marginBottom: 8,
  },
  label: {
    fontSize: 14,
    fontWeight: "700",
    color: "#333",
    marginBottom: 8,
    marginTop: 12,
  },
  input: {
    backgroundColor: "#f7f7f7",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 14,
    color: "#111",
    borderWidth: 1,
    borderColor: "#e5e5e5",
  },
  groupCard: {
    backgroundColor: "#fafafa",
    borderWidth: 1,
    borderColor: "#ececec",
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  actionsRow: {
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    marginTop: 10,
  },
  emptyText: {
    color: "#777",
    fontSize: 14,
    fontWeight: "600",
    marginTop: 4,
  },
  removeButton: {
    marginTop: 14,
    alignSelf: "flex-start",
    backgroundColor: "#ef4444",
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 10,
  },
  removeButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
  },
  deleteVendorButton: {
    marginTop: 20,
    alignSelf: "flex-start",
    backgroundColor: "#dc2626",
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderRadius: 10,
  },
  deleteVendorButtonText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 13,
  },
  saveButton: {
    marginTop: 28,
    backgroundColor: "#f59e0b",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  previewImage: {
    width: "100%",
    height: 180,
    borderRadius: 12,
    backgroundColor: "#d1d5db",
  },
  emptyImageBox: {
    width: "100%",
    height: 180,
    borderRadius: 12,
    backgroundColor: "#d1d5db",
  },
});

export default styles;